version: '3'
services:
  application:
    build:
        context: .
        dockerfile: Dockerfile
        target: dev
    image: nodejs 
    env_file:
      - .env
    container_name: application
    restart: always
    ports:
      - 3000:3000
    networks:
      - metrics
    command: npm run start
  prometheus:
    image: prom/prometheus
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - metrics
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 8000:3000
    networks:
      - metrics
networks:
  metrics:
    driver: bridge
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: 'grupo5'
  #     POSTGRES_USER: 'user'
  #     POSTGRES_PASSWORD: 'password'
  #   expose:
  #     - '5432'
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     # So that our database's state is persisted locally
  #     - ./postgres-dump:/docker-entrypoint-initdb.d
  #     # Where our data will be persisted
  #     - my-db:/var/lib/posgresql
# Names our volume
# volumes:
#   my-db:
